/* qoz.h - C bindings for libqoz, generated by cbindgen from qoz-capi/src/lib.rs.
 * Do not edit by hand - regenerate with:
 *   cbindgen --config cbindgen.toml --output include/qoz.h
 * run from the qoz-capi/ directory.
 */

#ifndef QOZ_H
#define QOZ_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Description of a raw pixel buffer / decoded image.
 */
typedef struct QozDesc {
    uint32_t width;
    uint32_t height;
    /**
     * 1 = grey, 2 = grey+alpha, 3 = rgb, 4 = rgba
     */
    uint8_t channels;
    /**
     * 0 = srgb, 1 = linear (purely informative)
     */
    uint8_t colorspace;
} QozDesc;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Description of the last error on the calling thread, or NULL if the
 * most recent `qoz_*` call on this thread succeeded. The pointer is only
 * valid until the next `qoz_*` call on the same thread.
 */
 const char *qoz_last_error(void);

/**
 * Library version string (e.g. "0.1.0"), NUL-terminated, static storage.
 */
 const char *qoz_version(void);

/**
 * Parse just the header of an in-memory `.qoz` buffer into `*desc`,
 * without decoding pixel data. Returns `true` on success. `data` must
 * point to at least `size` readable bytes.
 *
 * # Safety
 * `data` must be valid for reads of `size` bytes, and `desc` must be a
 * valid, aligned, writable `QozDesc*`.
 */
 bool qoz_get_desc(const uint8_t *data, size_t size, struct QozDesc *desc);

/**
 * Decode an in-memory `.qoz` buffer. On success, fills `*desc` and
 * returns a freshly allocated pixel buffer of exactly
 * `desc->width * desc->height * channels` bytes (row-major, interleaved).
 * Returns NULL on error - call [`qoz_last_error`] for details.
 *
 * Free the returned buffer with `qoz_free(ptr, width*height*channels)`.
 *
 * # Safety
 * `data` must be valid for reads of `size` bytes, and `desc` must be a
 * valid, aligned, writable `QozDesc*`.
 */
 uint8_t *qoz_decode(const uint8_t *data, size_t size, struct QozDesc *desc);

/**
 * Encode raw pixels (`desc->width * desc->height * channels` bytes,
 * row-major interleaved) into a new `.qoz` buffer.
 *
 * - `level`: zstd compression level (try 9); mostly affects ratio and encode time, not decode
 *   time.
 * - `tile_rows`: rows per independently-decodable tile; 0 = pick automatically from available CPU
 *   cores.
 *
 * On success, writes the encoded length to `*out_size` and returns a
 * malloc'd buffer; free it with `qoz_free(ptr, *out_size)`. Returns NULL
 * on error - call [`qoz_last_error`] for details.
 *
 * # Safety
 * `pixels` must be valid for reads of `desc->width * desc->height *
 * channels` bytes. `desc` and `out_size` must be valid, aligned, and (for
 * `out_size`) writable.
 */

uint8_t *qoz_encode(const uint8_t *pixels,
                    const struct QozDesc *desc,
                    int32_t level,
                    uint32_t tile_rows,
                    size_t *out_size);

/**
 * Upper bound on the encoded size for the given dimensions - useful for
 * pre-allocating a buffer on the caller's side, if desired. `channels`
 * must be 1-4; returns 0 for an invalid channel count.
 */
 size_t qoz_max_encoded_len(uint32_t width, uint32_t height, uint8_t channels, uint32_t tile_rows);

/**
 * Free a buffer returned by [`qoz_decode`] or [`qoz_encode`]. `len` must
 * be exactly the byte length documented for that call. Safe to call with
 * `ptr == NULL` (no-op).
 *
 * # Safety
 * `ptr` must either be NULL, or a pointer previously returned by
 * `qoz_decode`/`qoz_encode` that has not already been freed, and `len`
 * must exactly match the length documented for that call.
 */
 void qoz_free(uint8_t *ptr, size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QOZ_H */
