[package]
name = "qoz-cli"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "qoz"
path = "src/main.rs"

[dependencies]
qoz = { path = "../qoz" }
clap = { version = "4.5.4", features = ["derive"] }
qoi = "0.4"
memmap2 = "0.9.11"
anyhow = "1.0.104"

[dependencies.image]
version = "0.25.10"
default-features = false
features = ["avif-native", "png", "jpeg", "webp", "gif", "bmp", "tiff", "tga", "dds", "exr", "hdr", "ico", "pnm", "qoi", "rayon"]
